export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: "user/SET_CURRENT_USER",

  USER_LOGIN_REQUEST: "user/USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "user/USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILED: "user/USER_LOGIN_FAILED",

  USER_REGISTER_REQUEST: "user/USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "user/USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILED: "user/USER_REGISTER_FAILED",

  USER_LOGOUT: "user/USER_LOGOUT",
};
